### ISSUE TITLE
建议：书中缩减前端章节，增加.NET6部分

### ISSUE THREAD

**Issue by wuming123057** [SpringFarSoft/Book#19]
书中缩减前端章节，增加.NET6部分

**Comment by anjoy8** [comment]
因为书名是.NET5

**Comment by 16cm** [comment]
复议，我个人认为，没必要讲解前端，就好比，专业的人做专业的事儿，你宁可加入：哪些常用中间件、该怎么用，日志log4N、本书最后甚至还延引SOA、DDD思想和微服务落地的简单延伸等都比嵌入前端的强。。。
