### ISSUE TITLE
【第4章】递归获取配置信息数组 的方法中添加对Bind的注释让人知道 是用了哪个包的扩展方法

### ISSUE THREAD

**Issue by 16cm** [SpringFarSoft/Book#21]
递归获取配置信息数组 的方法中添加对Bind的注释让人知道 是用了哪个包的扩展方法

![image](https://user-images.githubusercontent.com/20642702/159910299-20097b6d-88ea-4745-8d50-06ac1a590f08.png)

**Comment by MrChuJiu** [comment]
代码上面有说明，印刷导致揉在一起的，已处理
