### ISSUE TITLE
写书严谨点，把代码里面的注释没有标注的内容的注释语句删掉

### ISSUE THREAD

**Issue by 16cm** [SpringFarSoft/Book#22]
写书严谨点，把代码里面的注释没有标注的内容的注释语句删掉，比如：
```csharp
 /// <summary>
/// 解析
 /// </summary>
/// <param name="jwtStr"></param>
/// <returns></returns>
public static TokenModelJwt SerializeJwt(string jwtStr)
{...}
```

注释中标注了：
解析，那解析了什么？（我能从上下文知道，但是也别那么省略）           【你是为了 出版社省墨水吗？】
`<param name="jwtStr"></param>`    这个没有写注释的可以删掉    【这里倒是没考虑出版社那个的墨水了】

我个人意见，仅供参考

**Comment by MrChuJiu** [comment]
嗯，将会进行改正，非常感谢提出意见
