### ISSUE TITLE
日志框架Serilog遗漏

### ISSUE THREAD

**Issue by boogaloo-jw** [SpringFarSoft/Book#24]
P8，知识点第10条：使用Serilog日志框架，集成原生ILogger接口做日志记录。
但我翻遍书本和源码，并未找到该知识点的介绍和运用。
后续请补充啊……
![Uploading 31adb29333306a2a0a27da564afe66f.jpg…]()

**Comment by MrChuJiu** [comment]
非常抱歉，当时在设计的时候打算用Serilog，后来写代码就写没了。哈哈哈
